Senses = {
    '1' : {'N':[2], 'ADJ':[1],},
    '1st' : {'ADJ':[1]},
    '2' : {'N':[2], 'ADJ':[1]},
    '3' : {'N':[2], 'ADJ':[1]},
    '4' : {'N':[2], 'ADJ':[1]},
    '5' : {'N':[2], 'ADJ':[1]},
    '6' : {'N':[2], 'ADJ':[1]},
    '7' : {'N':[2], 'ADJ':[1]},
    '90' : {'ADJ':[1],},
    'able' : {'ADJ':[1],},
    'about' : {'ADV':[1],},
    'above' : {'ADJ':[1],},
    'accurate' : {'ADJ':[1],},
    'aesal' : {'see':'easel'},
    'after' : {'ADV':[1,2],},
    'again' : {'ADV':[1]},
    'ahead' : {'ADV':[1]},
    'ahllway' : {'see':'hallway'},
    'ahllways' : {'see':'hallways'},
    'aisle' : {'N':[1],},
    'aisles' : {'N':[('aisle',[1])],},
    'aleft' : {'see':'left'},
    'alk' : {'see':'walk'},
    'all' : {'ADJ':[1], 'ADV':[1]},
    'all the way' : {'see':'all'},
    'all of the way' : {'see':'all'},
    'alley' : {'N':[1]},
    'alleys' : {'N':[('alley',[1])]},
    'almost' : {'ADV':[1]},
    'along' : {'ADV':[1]},
    'also' : {'ADV':[1]},
    'although' : {'ADV':[1]},
    'am' : {'V':[('be',[1,2,3,4,5])]},
    'amek' : {'see':'make'},
    'anopther' : {'see':'another'},
    'another' : {'ADJ':[1,2]},
    'antoher' : {'see':'another'},
    'any' : {'ADJ':[2]},
    'appears' : {'V':[('appear',[1,2])]},
    'are' : {'V':[('be',[1,2,3,4,5])]},
    'area' : {'N':[1]},
    'areas' : {'N':[('area',[1])]},
    'aright' : {'see':'right'},
    'around' : {'ADV':[6]},
    'as' : {'ADV':[1]},
    'away' : {'ADJ':[1], 'ADV':[1]},
    'back' : {'N':[1], 'ADJ':[1], 'ADV':[1,2]},
    'bar' : {'see':'bare'},
    'bare' : {'ADJ':[4]},
    'be' : {'V':[1,2,3,4,5]},
    'begins' : {'V':[('begin',[2])]},
    'behind' : {'ADV':[1]},
    'believe' : {'V':[1]},
    'bench' : {'N':[1]},
    'between' : {'ADV':[2]},
    'beyond' : {'ADV':[1,2]},
    'black' : {'ADJ':[1]},
    'blank' : {'ADJ':[1]},
    'block' : {'N':[2]},
    'blocks' : {'N':[('block',[2])]},
    'blue' : {'ADJ':[1]},
    'both' : {'ADJ':[1]},
    'branch' : {'N':[3], 'V':[2]},
    'branches' : {'N':[('branch',[3])], 'V':[('branch',[2])]},
    'branching' : {'N':[1], 'V':[('branch',[2])]},
    'brick' : {'N':[1],},
    'bricked' : {'see':'red'},
    'brings' : {'V':[('bring',[1,2,3,5])],},
    'brown' : {'ADJ':[1]},
    'but' : {'ADV':[1]},
    'buterfly' : {'see':'butterfly'},
    'butterflies' : {'N':[('butterfly',[1])]},
    'butterfly' : {'N':[1]},
    'butterflys' : {'N':[('butterfly',[1])]},
    'butterlfy' : {'see':'butterfly'},
    'bvlue' : {'see':'blue'},
    'came' : {'V':[('come',[1,2])]},
    'can' : {'V':[1]},
    'carpet' : {'N':[1]},
    'carpeted' : {'ADJ':[1]},
    'carpeting' : {'N':[1]},
    'cement' : {'N':[1]},
    'certain' : {'ADJ':[1,2]},
    'chair' : {'N':[1]},
    'chairs' : {'N':[('chair',[1])]},
    'charred' : {'ADJ':[1]},
    'choice' : {'N':[3]},
    'click' : {'N':[2]},
    'close' : {'ADJ':[1]},
    'closer' : {'ADJ':[('close',[1])], 'ADV':[1]},
    'closest' : {'ADJ':[('close',[1])], 'ADV':[1]},
    'clownfish' : {'see':'fish'},
    'coat' : {'N':[1]},
    'coatrack' : {'N':[1]},
    'colored' : {'ADJ':[1]},
    'come' : {'V':[1,2,3,4]},
    'completely' : {'ADV':[1]},
    'conataining' : {'see':'containing'},
    'conatains' : {'see':'contains'},
    'conatins' : {'see':'contains'},
    'concrete' : {'N':[1], 'ADJ':[2]},
    'contain' : {'V':[1]},
    'containa' : {'see':'contains'},
    'contained' : {'V':[('contain',[1])]},
    'containg' : {'see':'containing'},
    'containing' : {'V':[('contain',[1])]},
    'contains' : {'V':[('contain',[1])]},
    'continue' : {'V':[1,4]},
    'continuing' : {'V':[('continue',[1,4])]},
    'corner' : {'N':[4]},
    'corridor' : {'N':[1]},
    'couple' : {'N':[1]},
    'course' : {'N':[5]},
    'covered' : {'ADJ':[1]},
    'crosses' : {'V':[('cross',[1,2])]},
    'crossing' : {'N':[4], 'V':[('cross',[1,2])]},
    'dark' : {'ADJ':[2]},
    'dead end' : {'N':[1]},
    'dead' : {'see':'dead end'},
    'deadend' : {'see':'dead end'},
    'description' : {'N':[1]},
    'direction' : {'N':[1,2,3,6]},
    'directions' : {'N':[('direction',[6])]},
    'directly' : {'ADV':[1]},
    'distance' : {'N':[2]},
    'down' : {'ADV':[1]},
    'each' : {'ADJ':[1]},
    'easel' : {'N':[1]},
    'easle' : {'see':'easel'},
    'edge' : {'N':[6]},
    'efficient' : {'ADJ':[1]},
    'eiffel' : {'N':[1]},
    'eiffel tower' : {'N':[1]},
    'either' : {'ADV':[1]},
    'empty' : {'ADJ':[1]},
    'end' : {'N':[1], 'V':[1]},
    'ending' : {'V':[('end',[1])]},
    'ends' : {'V':[('end',[1])]},
    'enter' : {'V':[1]},
    'epink' : {'see':'pink'},
    'eventually' : {'ADV':[1]},
    'exit' : {'N':[1,2], 'V':[1]},
    'expanse' : {'N':[2]},
    'face' : {'V':[5]},
    'faces' : {'V':[('face',[5])]},
    'facing' : {'V':[('face',[3,5])]},
    'fail' : {'V':[2]},
    'far' : {'ADJ':[1], 'ADV':[2,3]},
    'farther' : {'ADJ':[1], 'ADV':[2]},
    'farthest' : {'ADJ':[1], 'ADV':[1]},
    'fave' : {'see':'face'},
    'few' : {'ADJ':[1]},
    'finally' : {'ADV':[2]},
    'find' : {'V':[3]},
    'finding' : {'V':[('find',[3])]},
    'first' : {'ADJ':[1], 'ADV':[1]},
    'fish' : {'N':[1]},
    'fishy' : {'see':'fish'},
    'five' : {'N':[1], 'ADJ':[1]},
    'flooored' : {'see':'floored'},
    'floor' : {'N':[1],},
    'floord' : {'see':'floored'},
    'floored' : {'ADJ':[1]},
    'flooring' : {'N':[1,2]},
    'floors' : {'N':[('floor',[1])]},
    'flor' : {'see':'floor'},
    'florr' : {'see':'floor'},
    'flower' : {'N':[2]},
    'flowerd' : {'see':'flowered'},
    'flowered' : {'ADJ':[1]},
    'flowers' : {'N':[('flower',[1])]},
    'follow' : {'V':[4]},
    'followe' : {'see':'followed'},
    'following' : {'ADJ':[1]},
    'foored' : {'see':'floored'},
    'forces' : {'V':[('force',[1])]},
    'forward' : {'ADJ':[1,2], 'ADV':[1]},
    'four' : {'N':[1], 'ADJ':[1]},
    'fourth' : {'ADJ':[1]},
    'foward' : {'see':'forward'},
    'fron' : {'see':'front'},
    'front' : {'N':[2,3,10], 'ADJ':[1,2]},
    'furniture' : {'N':[1]},
    'furnitute' : {'see':'furniture'},
    'further' : {'ADJ':[2], 'ADV':[3]},
    'futon' : {'N':[1]},
    'fwd' : {'see':'forward'},
    'get' : {'V':[5]},
    'go' : {'V':[1]},
    'goi' : {'see':'go'},
    'goin' : {'see':'going'},
    'going' : {'V':[('go',[1,2])]},
    'grass' : {'N':[1]},
    'grassy' : {'ADJ':[1]},
    'gray' : {'ADJ':[1]},
    'green' : {'ADJ':[1]},
    'grey' : {'ADJ':[1]},
    'greyt' : {'see':'grey'},
    'hal' : {'see':'hall'},
    'halfway' : {'ADJ':[1], 'ADV':[1]},
    'hall' : {'N':[1]},
    'halllway' : {'see':'hallway'},
    'halls' : {'N':[('hall',[1])]},
    'hallway' : {'N':[1]},
    'hallways' : {'N':[('hallway',[1])]},
    'hallwyas' : {'see':'hallways'},
    'hang' : {'see':'take'},
    'hanging' : {'N':[1]},
    'hangings' : {'N':[('hanging',[1])]},
    'has' : {'V':[('have',[1])]},
    'hat rack' : {'see': 'hatrack'},
    'hatrack' : {'N':[1]},
    'have' : {'V':[1]},
    'having' : {'V':[('have',[1])]},
    'head' : {'V':[1]},
    'here' : {'N':[1], 'ADJ':[1], 'ADV':[1]},
    'hexagonal' : {'ADJ':[1]},
    'hexagonally' : {'see':'hexagonal'},
    'hit' : {'V':[5]},
    'hold' : {'V':[6]},
    'honeycomb' : {'N':[1]},
    'however' : {'ADV':[2]},
    'images' : {'N':[('image',[2])]},
    'immediate' : {'ADJ':[1]},
    'immediately' : {'ADV':[1]},
    'inersection' : {'see':'intersection'},
    'infront' : {'see':'front'},
    'interection' : {'see':'intersection'},
    'interesction' : {'see':'intersection'},
    'interesection' : {'see':'intersection'},
    'interesects' : {'see':'intersects'},
    'interseciton' : {'see':'intersection'},
    'intersect' : {'V':[1]},
    'intersected' : {'V':[('intersect',[1])]},
    'intersecting' : {'V':[('intersect',[1])], 'ADJ':[1]},
    'intersectino' : {'see':'intersection'},
    'intersection' : {'N':[2]},
    'intersections' : {'N':[('intersection',[2])]},
    'intersects' : {'V':[('intersect',[1])]},
    'intesection' : {'see':'intersection'},
    'is' : {'V':[('be',[1,2,3,4,5])]},
    'junction' : {'N':[1]},
    'juncture' : {'N':[2]},
    'just' : {'ADV':[2,5]},
    'keep' : {'V':[1,2]},
    'key' : {'ADJ':[1]},
    'laft' : {'see':'left'},
    'lamp' : {'N':[2]},
    'lampl' : {'see':'lamp'},
    'lampshade' : {'N':[1]},
    'last' : {'ADJ':[2], 'ADV':[2]},
    'leading' : {'V':[('lead',6)]},
    'leads' : {'V':[('lead',6)]},
    'left' : {'N':[1,5], 'ADJ':[1], 'ADV':[1]},
    'lft' : {'see':'left'},
    'like' : {'ADJ':[1]},
    'little' : {'N':[1]},
    'locate' : {'V':[2]},
    'located' : {'V':[('locate',[2])], 'ADJ':[1]},
    'long' : {'ADJ':[2]},
    'longer' : {'ADJ':[1]},
    'longetr' : {'see':'longer'},
    'look' : {'V':[1,4]},
    'looking' : {'V':[('look',[1,4])], 'ADJ':[1]},
    'lovely' : {'ADJ':[1]},
    'make' : {'V':[16]},
    'makea' : {'see':'make'},
    'makes' : {'V':[('make',[16])]},
    'many' : {'ADJ':[1]},
    'match' : {'V':[1]},
    'maybe' : {'ADV':[1]},
    'meet' : {'V':[3]},
    'meets' : {'V':[('meet',[3])]},
    'middle' : {'N':[1,2], 'ADJ':[1,2]},
    'monarch' : {'N':[2]},
    'more' : {'ADJ':[1,2,3]},
    'most' : {'ADJ':[1,2]},
    'move' : {'N':[4], 'V':[1]},
    'movement' : {'N':[3]},
    'movements' : {'N':[('movement',[3])]},
    'moving' : {'V':[('move',[1])]},
    'near' : {'ADJ':[1]},
    'need' : {'V':[1]},
    'new' : {'ADJ':[2]},
    'next' : {'ADJ':[3], 'ADV':[1]},
    'no' : {'ADJ':[1]},
    'normal' : {'ADJ':[1]},
    'not' : {'ADV':[1]},
    'notably' : {'ADV':[1]},
    'nothing' : {'N':[1]},
    'now' : {'ADV':[4]},
    'object' : {'N':[1]},
    'objects' : {'N':[('object',[1])]},
    'octagon' : {'N':[1]},
    'octagons' : {'N':[('octagon',[1])]},
    'off' : {'ADV':[1,2]},
    'oine' : {'see':'one'},
    'olive' : {'ADJ':[1]},
    'on' : {'ADV':[1]},
    'once' : {'ADV':[1,2]},
    'one' : {'ADJ':[1,2]},
    'only' : {'ADJ':[1,2], 'ADV':[2]},
    'opening' : {'N':[1]},
    'opens' : {'V':[('open',[8])]},
    'opposite' : {'ADJ':[1]},
    'or' : {'N':[1,2]},
    'orange' : {'ADJ':[1]},
    'orient' : {'V':[3]},
    'oriented' : {'ADJ':[1]},
    'originated' : {'V':[('originate',[3])]},
    'other' : {'ADJ':[1,2]},
    'p' : {'see':'position'},
    'p4' : {'see':'4'},
    'p6' : {'see':'6'},
    'painting' : {'N':[1]},
    'painting easel' : {'see':'easel'},
    'paragraph' : {'N':[1]},
    'pass' : {'V':[1]},
    'passing' : {'V':[('pass',[1])]},
    'patch' : {'N':[2]},
    'path' : {'N':[2,3,4]},
    'paths' : {'N':[('path',[2,3,4])]},
    'pcitures' : {'see':'picaitures'},
    'perpendicualr' : {'see':'perpendicular'},
    'perpendicular' : {'ADJ':[1]},
    'perspective' : {'N':[1]},
    'pics' : {'N':[('pic',[2])]},
    'pictures' : {'N':[('picture',[2])]},
    'pieaces' : {'see':'pieces'},
    'piece' : {'N':[2]},
    'pieces' : {'N':[('piece',[2])]},
    'pink' : {'ADJ':[1]},
    'place' : {'N':[1], 'V':[1]},
    'placed' : {'ADJ':[1]},
    'places' : {'N':[('place',[1])]},
    'plain' : {'ADJ':[3]},
    'pnk' : {'see':'pink'},
    'point' : {'N':[2]},
    'pole' : {'N':[1]},
    'portion' : {'N':[1]},
    'pos' : {'see':'position'},
    'position' : {'N':[1], 'V':[1]},
    'possible' : {'ADJ':[2]},
    'possibly' : {'ADV':[1]},
    'post' : {'N':[4]},
    'postion' : {'see':'position'},
    'postition' : {'see':'position'},
    'previous' : {'ADJ':[3]},
    'print' : {'see' : 'carpeted'},
    'probably' : {'ADV':[1]},
    'put' : {'V':[1]},
    'quite' : {'ADV':[2]},
    'rack' : {'N':[1]},
    'reach' : {'V':[1]},
    'reached' : {'V':[('reach',[1])]},
    'recall' : {'V':[1]},
    'rech' : {'see':'reach'},
    'red' : {'ADJ':[1]},
    'regardless' : {'ADV':[1]},
    'regular' : {'ADJ':[3]},
    'remember' : {'V':[1]},
    'resume' : {'V':[1]},
    'right' : {'N':[3,4], 'ADJ':[1,2], 'ADV':[4]},
    'roack' : {'see':'rock'},
    'road' : {'N':[1]},
    'rock' : {'N':[2]},
    'room' : {'N':[1]},
    'rose' : {'N':[1], 'ADJ':[1]},
    'roses' : {'N':[('rose',[1])]},
    'rotate' : {'V':[1]},
    'route' : {'N':[1]},
    'rt' : {'see':'right'},
    'running' : {'V':[('run',[3])]},
    'same' : {'ADJ':[1,2]},
    'second' : {'ADJ':[1], 'ADV':[1]},
    'section' : {'N':[4]},
    'sections' : {'N':[('section',[4])]},
    'see' : {'V':[1]},
    'segements' : {'see':'segments'},
    'segment' : {'N':[1]},
    'segments' : {'N':[('segment',[1])]},
    'segmentsm' : {'see':'segments'},
    'series' : {'N':[1]},
    'seven' : {'N':[1], 'ADJ':[1]},
    'several' : {'ADJ':[1]},
    'short' : {'ADJ':[2]},
    'shorter' : {'ADJ':[('short',[2])]},
    'side' : {'N':[1]},
    'sides' : {'N':[('side',[1])]},
    'simply' : {'ADV':[1]},
    'single' : {'ADJ':[1]},
    'six' : {'N':[1], 'ADJ':[1]},
    'so' : {'ADV':[2]},
    'sofa' : {'N':[1]},
    'solid' : {'ADJ':[5]},
    'some' : {'ADJ':[1],},
    'something' : {'N':[1]},
    'sort' : {'N':[1]},
    'space' : {'N':[5]},
    'spaces' : {'N':[('space',[5])]},
    'spce' : {'see':'space'},
    'spot' : {'N':[1]},
    'square' : {'N':[3]},
    'stand' : {'N':[5], 'V':[3]},
    'standing' : {'V':[('stand',[3])]},
    'start' : {'V':[1,2]},
    'station' : {'N':[4]},
    'stay' : {'V':[1]},
    'stem' : {'N':[3]},
    'step' : {'N':[2]},
    'steps' : {'N':[('step',[2])]},
    'still' : {'ADV':[1]},
    'stone' : {'N':[2], 'ADJ':[1]},
    'stool' : {'N':[1]},
    'stop' : {'V':[1]},
    'straight' : {'ADJ':[2,8], 'ADV':[1,3]},
    'street' : {'N':[1]},
    'streets' : {'N':[('street',[1])]},
    'such' : {'ADJ':[1,2,3]},
    'sure' : {'ADJ':[1]},
    't' : {'N':[5]}, 
    "' t '" : {'see':'t'},
    'take' : {'V':[1,11,40]},
    'then' : {'ADV':[1]},
    'there' : {'N':[1], 'ADV':[1]},
    'thing' : {'N':[3,9]},
    'think' : {'V':[1]},
    'third' : {'ADJ':[1], 'ADV':[1]},
    'though' : {'ADV':[1]},
    'thre' : {'see':'three'},
    'three' : {'N':[1], 'ADJ':[1]},
    'tiems' : {'see':'times'},
    'tile' : {'N':[1]},
    'tiled' : {'ADJ':[1]},
    'tiles' : {'N':[('tile',[1])]},
    'time' : {'N':[1]},
    'times' : {'N':[('time',[1])]},
    'tke' : {'see':'take'},
    'together' : {'ADV':[2]},
    'too' : {'ADV':[2]},
    'top' : {'N':[1]},
    'tower' : {'N':[1]},
    'towers' : {'N':[('tower',[1])]},
    'travel' : {'V':[1]},
    'tricky' : {'ADJ':[2]},
    'tunr' : {'see':'turn'},
    'turn' : {'N':[1,2], 'V':[1]},
    'turned' : {'V':[('turn',[1])]},
    'turning' : {'V':[('turn',[1])]},
    'turns' : {'N':[('turn',[1,2])], 'V':[('turn',[1])]},
    'twice' : {'ADV':[1]},
    'two' : {'N':[1], 'ADJ':[1]},
    'uncertain' : {'ADJ':[2]},
    'up' : {'ADV':[1]},
    'vacant' : {'ADJ':[2]},
    'very' : {'ADJ':[1], 'ADV':[2]},
    'view' : {'V':[1]},
    'visible' : {'ADJ':[1]},
    'walk' : {'V':[1]},
    'walked' : {'V':[('walk',[1])]},
    'walking' : {'V':[('walk',[1])]},
    'walkway' : {'N':[1]},
    'wall' : {'N':[1]},
    'wall hanging' : {'N':[('hanging',[1])]},
    'walled' : {'V':[('wall',[1])], 'ADJ':[1]},
    'walls' : {'N':[('wall',[1])]},
    'wander' : {'V':[3]},
    'was' : {'V':[('be',[1,2,3,4,5,6])]},
    'wawya' : {'see':'way'},
    'way' : {'N':[7,8]},
    'ways' : {'N':[7,8]},
    'when' : {'ADV':[1]},
    'where' : {'ADV':[1]},
    'white' : {'ADJ':[1]},
    'winding' : {'ADJ':[1,2]},
    'wlak' : {'see':'walk'},
    'wood' : {'N':[1]},
    'wooden' : {'ADJ':[1]},
    'yellow' : {'ADJ':[1]},
    }

Senses2 = {
    '2nd' : {'N':[2], 'ADJ':[1]},
    '3rd' : {'N':[2], 'ADJ':[1]},
    '4th' : {'N':[2], 'ADJ':[1]},
    '180' : {'ADJ' : [1]},
    'l' : {'N':[5]},
    'woodlike' : {'see' : 'wooden'},
    'granite' : {'see' : 'rock'},
    'hex' : {'see' : 'hexagonal'},
    'hexagons' : {'see' : 'hexagonal'},
    'hardwood' : {'see' : 'wooden'},
    'dirt' : {'see' : 'wooden'},
    'flowery' : {'see' : 'flowered'},
    'arrive' : {'see' : 'reach'},
    'meet' : {'see' : 'reach'},
    'meet up' : {'see' : 'intersect'},
    'center' : {'see' : 'front'},
    'onward' : {'see' : 'forward'},
    'onwards' : {'see' : 'forward'},
    'forwards' : {'see' : 'forward'},
    'step' : {'see' : 'stop'},
    'wander' : {'see' : 'find'},
    'wind' : {'see' : 'winding'},
    'spot' : {'see' : 'square'},
    'center' : {'V' : [3]},
    'sitting' : {'see' : 'stand'},
    'chair with a back' : {'N':[('straight chair',[1])]},
    'dining chair' : {'N':[('straight chair',[1])]},
    'coat/hat stand' : {'see' : 'coatrack'},
    'coat hanger' : {'see' : 'coatrack'},
    'coat hanger looking thing' : {'see' : 'coatrack'},
    'clothes hanger' : {'see' : 'coatrack'},
    'candlestand' : {'see' : 'coatrack'},
    'board' : {'see' : 'easel'},
    'art board' : {'see' : 'easel'},
    'artist board' : {'see' : 'easel'},
    'eisle' : {'see' : 'easel'},
    "painter ' s board" : {'see' : 'easel'},
    'painting board' : {'see' : 'easel'},
    'painting eisle' : {'see' : 'easel'},
    'painters stand' : {'see' : 'easel'},
    'painting stand' : {'see' : 'easel'},
    'painting thing' : {'see' : 'easel'},
    'thing you put the canvas on to paint' : {'see' : 'easel'},
    'thing painters paint on' : {'see' : 'easel'},
    'thing you paint pictures on' : {'see' : 'easel'},
    'ground' : {'see' : 'floor'},
    'floor lamp' : {'see' : 'lamp'},
    'lampstand' : {'see' : 'lamp'},
    'lamppost' : {'see' : 'lamp'},
    'lamp post' : {'see' : 'lamp'},
    'poster' : {'see' : 'painting'},
    'wallpaper' : {'see' : 'painting'},
    'nearest' : {'see' : 'next'},
    'make sure' : {'see' : 'orient'},
    'be sure' : {'see' : 'orient'},
    'heading' : {'see' : 'orient'},
    'start out' : {'see' : 'orient'},
    'panel' : {'see' : 'segment'},
    'rectangle' : {'see' : 'segment'},
    'tiling' : {'see' : 'tile'},
    'scale' : {'see' : 'tile'},
    'leg' :{'see' : 'portion'},
    'pathed' : {'see' : 'way'},
    'destination' : {'see':'position'},
    'location' : {'see':'position'},
    'adjoining' : {'see' : 'next'},
    'stay' : {'see' : 'stop'},
    'remain' : {'see' : 'stop'},
    'center' : {'see' : 'middle'},
    'opportunity' : {'see' : 'turn'},
    'stretch' :{'see' : 'portion'},
    'part' :{'see' : 'portion'},
    'bit' :{'see' : 'portion'},
    'surrounded' : {'V' : [1]},
    'longest' : {'ADJ': [('long',[2])]},
    'shortest' : {'ADJ':[('short',[2])]},
    'proceed' : {'see' : 'head'},
    }

Senses3 = {
    'army' : {'see' : 'honeycomb'},
    'canvas' :  {'see' : 'concrete'},
    'fishes' : {'see': 'fish'},
    'puke' : {'see' : 'honeycomb'},
    'turtle shell' : {'see' : 'hexagonal'},
}
